---
name: ci

on:
  push:
    branches:
      - feature/**

env:
  TZ: Asia/Tokyo

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}

      - name: install dependent modules
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: bun install

      - name: cache modules
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}

  lint:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: restore cache 
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}

      - name: exit if cache does not hit
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: lint
        run: bun lint
      
  unit_test:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: restore cache 
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}

      - name: exit if cache does not hit
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: test
        run: bun test
