---
name: ci

on:
  push:
    branches:
      - feature/**

env:
  TZ: Asia/Tokyo

jobs:
  unit_test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: bun install
        run: bun install

      - name: test
        run: bun test
